[package]
name = "tefi-oracle"
version = "0.2.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Common TeFi oracle types"

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false

[dependencies]
cosmwasm-std = { version = "0.16.2" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }
cosmwasm-bignumber = "2.2.0"
